---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: rhel7
    image: registry.access.redhat.com/rhel7:7.9
    pre_build_image: true
provisioner:
  name: ansible
  options:
    'vault-id': '@${MOLECULE_SCENARIO_DIRECTORY}/vault.pw'
    'extra-vars': '@${MOLECULE_SCENARIO_DIRECTORY}/rhsm_vars.yml'
verifier:
  name: ansible
