---
- name: Prepare
  hosts: all
  tasks:
  - name: Register with RHSM
    redhat_subscription:
      username: "{{ rhsm_username }}"
      password: "{{ rhsm_password }}"
      pool: "{{ rhsm_pool }}"
      state: present
  
  - name: Install Dependencies - Yum
    yum:
      name: sudo
      state: present